"""Add print_details Method to Freebie Model

Revision ID: 40e2319e8a51
Revises: de2c8c31ab7f
Create Date: 2023-08-19 17:19:54.653554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e2319e8a51'
down_revision = 'de2c8c31ab7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
