"""fixed back_populates

Revision ID: de2c8c31ab7f
Revises: e256848f0940
Create Date: 2023-08-19 16:44:28.392322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2c8c31ab7f'
down_revision = 'e256848f0940'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
